# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.runs/synth_1/zc702_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.cache/wt [current_project]
set_property parent.project_path /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.4 [current_project]
set_property ip_output_repo /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/CCD_SYNC.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/DPRAM.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/DPRAM_BE.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/DPRAM_DUAL_CLOCK.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/FP32_ADDSUB.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/FP32_MUL.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/SHIFT.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/SPRAM.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/SPRAM_BE.v
  /home/mahmoudsamy/grad/ZC702/platform/Xilinx/SYNC_LATCH.v
  /home/mahmoudsamy/grad/ZC702/src/top/riscv.v
  /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.gen/sources_1/bd/zynq_bd/hdl/zynq_bd_wrapper.v
  /home/mahmoudsamy/grad/ZC702/zc702_top.v
}
read_vhdl -library xil_defaultlib {
  /home/mahmoudsamy/grad/ZC702/src/util/adder.vhd
  /home/mahmoudsamy/grad/ZC702/src/config.vhd
  /home/mahmoudsamy/grad/ZC702/src/ztachip_pkg.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/afifo.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/afifo2.vhd
  /home/mahmoudsamy/grad/ZC702/src/alu/alu.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/arbiter.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_apb_bridge.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_merge.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_merge_read.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_merge_write.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_ram_read.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_ram_write.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_read.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_split.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_split_read.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_split_write.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_stream_read.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_stream_write.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_write.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/axilite.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/peripherals/camera.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/cell.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/core.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/ddr_rx.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/ddr_tx.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/delay.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/delayi.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/delayv.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp_core.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp_fetch.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp_fifo.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp_gen.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp_gen_core.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp_sink.vhd
  /home/mahmoudsamy/grad/ZC702/src/dp/dp_source.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/falu.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/falu2.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/falu_core.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/falu_vector.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/fifo.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/fifow.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/fp12.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/fp2int.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/fp_floor.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/fpmax.vhd
  /home/mahmoudsamy/grad/ZC702/src/fpu/fpu.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/peripherals/gpio.vhd
  /home/mahmoudsamy/grad/ZC702/src/ialu/ialu.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/instr.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/instr_decoder2.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/instr_dispatch2.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/instr_fetch.vhd
  /home/mahmoudsamy/grad/ZC702/src/ialu/iregister_file.vhd
  /home/mahmoudsamy/grad/ZC702/src/ialu/iregister_ram.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/multiplier.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/pcore.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/ram2r1w.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/ramw.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/ramw2.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/register_bank.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/register_file.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/rom.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/shifter.vhd
  /home/mahmoudsamy/grad/ZC702/src/util/shifter_l.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/soc_base.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/sram.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/sram_core.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/stream.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/tcm.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/peripherals/time.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/peripherals/uart.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/peripherals/vga.vhd
  /home/mahmoudsamy/grad/ZC702/src/pcore/xregister_file.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/zc702_apb_uart_bridge.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/zc702_sysctrl.vhd
  /home/mahmoudsamy/grad/ZC702/src/top/ztachip.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_resize_read.vhd
  /home/mahmoudsamy/grad/ZC702/src/soc/axi/axi_resize_write.vhd
}
add_files /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.srcs/sources_1/bd/zynq_bd/zynq_bd.bd
set_property used_in_implementation false [get_files -all /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.gen/sources_1/bd/zynq_bd/ip/zynq_bd_ps7_0/zynq_bd_ps7_0.xdc]
set_property used_in_implementation false [get_files -all /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.gen/sources_1/bd/zynq_bd/zynq_bd_ooc.xdc]

read_ip -quiet /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.srcs/sources_1/ip/float_mul/float_mul.xci
set_property used_in_implementation false [get_files -all /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.gen/sources_1/ip/float_mul/float_mul_ooc.xdc]

read_ip -quiet /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.srcs/sources_1/ip/float_addsub/float_addsub.xci
set_property used_in_implementation false [get_files -all /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.gen/sources_1/ip/float_addsub/float_addsub_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mahmoudsamy/grad/ZC702/zc702.xdc
set_property used_in_implementation false [get_files /home/mahmoudsamy/grad/ZC702/zc702.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top zc702_top -part xc7z020clg484-1 -fanout_limit 400
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zc702_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zc702_top_utilization_synth.rpt -pb zc702_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
