# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.srcs/sources_1/ip/float_mul/float_mul.xci
# IP: The module: 'float_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.gen/sources_1/ip/float_mul/float_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_mul'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.srcs/sources_1/ip/float_mul/float_mul.xci
# IP: The module: 'float_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mahmoudsamy/grad/ZC702/ztachip_zc702/ztachip_zc702.gen/sources_1/ip/float_mul/float_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_mul'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
